'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
(async()=>{
 for(const file of ['frontend/auth.ts','auth.js','tests/auth_check.cjs'])assert.doesNotThrow(()=>new TextDecoder('utf-8',{fatal:true}).decode(fs.readFileSync(file)),`${file} must be valid UTF-8`);
 const source=require('typescript').transpileModule(fs.readFileSync('frontend/auth.ts','utf8'),{compilerOptions:{target:require('typescript').ScriptTarget.ES2020}}).outputText,calls=[];
 const context={Headers,Request,URL,session:{user:{role:'reviewer'},csrf_token:'session-token'},showLogin(){context.session=null;context.loginShown=true;},nativeFetch:async(input,init)=>{calls.push({input,init});return {status:200};}};
 vm.createContext(context);
 vm.runInContext(source.slice(source.indexOf('async function request('),source.indexOf('async function readSession(')),context);
 await context.request('/api/jobs',{method:'POST',body:'multipart-body'});assert.equal(calls[0].init.headers.get('X-CSRF-Token'),'session-token');assert.equal(calls[0].init.headers.get('Content-Type'),null);assert.equal(calls[0].init.credentials,'same-origin');
 await context.request('/api/jobs');assert.equal(calls[1].init.headers.has('X-CSRF-Token'),false);
 context.session.user.role='viewer';await assert.rejects(context.request('/api/jobs',{method:'POST'}),/viewer/);await context.request('/api/chat',{method:'POST'});
 context.nativeFetch=async()=>({status:401});await context.request('/api/jobs');assert.equal(context.loginShown,true);await assert.rejects(context.request('/api/jobs',{method:'POST'}),/masuk kembali/);
 vm.runInContext(source.slice(source.indexOf('async function readSession('),source.indexOf('async function signedIn(')),context);
 await assert.rejects(context.readSession({ok:true,json:async()=>({user:{role:'admin'},csrf_token:'token'})}),/akun tidak valid/);
 await assert.rejects(context.readSession({ok:true,json:async()=>({user:{role:'superadmin'},csrf_token:'token'})}),/sesi tidak valid/);
 // Viewer role must disable correction export even when syncControls enabled its radio.
 const roleNodes={resultCorrections:{disabled:false},resultAi:{disabled:false}};
 class RoleButton {}
 class RoleInput {}
 Object.setPrototypeOf(roleNodes.resultCorrections,RoleInput.prototype);Object.setPrototypeOf(roleNodes.resultAi,RoleInput.prototype);
 context.session={user:{role:'viewer'},csrf_token:'viewer-token'};
 Object.assign(context,{HTMLButtonElement:RoleButton,HTMLInputElement:RoleInput,HTMLFieldSetElement:function(){},document:{getElementById:id=>roleNodes[id]||null,querySelectorAll:()=>[]}});
 vm.runInContext(source.slice(source.indexOf('function applyRole('),source.indexOf('async function request(')),context);
 context.applyRole();assert.equal(roleNodes.resultCorrections.disabled,true);assert.equal(roleNodes.resultAi.disabled,false,'AI media switch remains accessible');
 // Exercise the actual password form handlers against an isolated DOM/API fixture.
 const elements={},listeners={};
 function node(id){return elements[id]??=(id==='passwordForm'?{reset(){for(const name of ['currentPassword','newPassword','confirmPassword'])node(name).value='';},reportValidity(){return true;}}:{value:'',textContent:'',disabled:false,querySelector(){return id==='loginTransitionLoader'?node('transitionTitle'):null;},style:{},classList:{toggle(){}},setAttribute(k){if(k==='disabled')this.disabled=true;},removeAttribute(k){if(k==='disabled')this.disabled=false;},setCustomValidity(value){this.validity=value;},reportValidity(){return !this.validity;},focus(){this.focused=true;},showModal(){this.open=true;},close(){this.open=false;listeners.close?.();},addEventListener(name,fn){listeners[name]=fn;}});}
 Object.assign(context,{el:node,HTMLDialogElement:function(){},HTMLFormElement:function(){},HTMLButtonElement:function(){},HTMLInputElement:function(){},HTMLElement:function(){}});
 const user={id:'fixture',username:'fixture',role:'admin',tenant_id:'local',tenant_name:'Local',display_name:'fixture',avatar_url:null};
 context.session={user,csrf_token:'old-token'};context.updatePasswordMeter=value=>{context.meterValue=value;};
 vm.runInContext(source.slice(source.indexOf("el('logoutButton'"),source.indexOf('const passwordForm =')),context);

 vm.runInContext(source.slice(source.indexOf('const passwordForm ='),source.indexOf('new MutationObserver')),context);
 const submit=()=>elements.passwordForm.onsubmit({preventDefault(){}});
 node('currentPassword').value='fixture-current';node('newPassword').value='fixture-new-password';node('confirmPassword').value='different';
 const before=calls.length;await submit();assert.equal(calls.length,before,'mismatch never reaches server');assert.match(node('passwordStatus').textContent,/tidak cocok/);
 node('confirmPassword').value=node('newPassword').value;
 context.nativeFetch=async(input,init)=>{calls.push({input,init});return {status:400,ok:false,json:async()=>({detail:'Password saat ini salah.'})};};
 await submit();assert.equal(context.session.csrf_token,'old-token','failure retains prior session');assert.equal(node('passwordSubmit').disabled,false);assert.match(node('passwordStatus').textContent,/salah/);
 let resolveChange,pendingCalls=0;context.nativeFetch=()=>{pendingCalls++;return new Promise(resolve=>{resolveChange=resolve;});};
 const pending=submit();assert.equal(node('passwordSubmit').disabled,true);assert.equal(node('saveNameBtn').disabled,true);assert.equal(node('avatarFileInput').disabled,true);await submit();assert.equal(pendingCalls,1,'double submit sends one request');
 resolveChange({status:200,ok:true,json:async()=>({user,csrf_token:'fresh-token'})});await pending;
 assert.equal(context.session.csrf_token,'fresh-token');assert.equal(node('currentPassword').value,'');assert.equal(node('confirmPassword').value,'');assert.match(node('passwordStatus').textContent,/Sesi lain/);
 context.nativeFetch=async(input,init)=>{calls.push({input,init});return {status:200};};await context.request('/api/jobs',{method:'POST'});assert.equal(calls.at(-1).init.headers.get('X-CSRF-Token'),'fresh-token');
  vm.runInContext(source.slice(source.indexOf('function renderProfile('),source.indexOf('async function signedIn(')),context);
 let selectedView;context.setView=async view=>{selectedView=view;return true;};
 await elements.profileButton.onclick();assert.equal(selectedView,'profile');assert.equal(node('passwordStatus').textContent,'');assert.equal(node('profileTitle').focused,true);assert.equal(node('profileUsername').textContent,'fixture');assert.equal(node('profileWorkspace').textContent,'Local');assert.equal(node('profileRole').textContent,'Administrator');assert.equal(node('accountAvatar').textContent,'FI');assert.equal(node('accountIdentity').textContent,'fixture');
 node('profileTitle').focused=false;node('passwordStatus').textContent='kept';context.setView=async()=>false;await elements.profileButton.onclick();assert.equal(node('profileTitle').focused,false,'blocked navigation never focuses hidden profile');assert.equal(node('passwordStatus').textContent,'kept');
 node('newPassword').value='leftover';node('newPassword').type='text';context.resetPasswordForm();assert.equal(node('newPassword').value,'');assert.equal(node('newPassword').type,'password');
 assert.equal(context.meterValue,'','reset updates strength meter');
 // Run real server-backed profile helper, including pending and failure behavior.
 vm.runInContext(source.slice(source.indexOf('async function saveProfile('),source.indexOf("el('newPassword'",source.indexOf('async function saveProfile('))),context);
 let resolveProfile,profileCalls=0;context.nativeFetch=()=>{profileCalls++;return new Promise(resolve=>{resolveProfile=resolve;});};
 const profileWait=context.saveProfile('/api/auth/profile',{method:'PATCH',body:'{}'},'nameSaveStatus','Saved');assert.equal(node('passwordSubmit').disabled,true);node('newPassword').value='fixture-next-password';node('confirmPassword').value='fixture-next-password';await submit();assert.equal(profileCalls,1,'password cannot overlap profile request');
 resolveProfile({status:200,ok:true,json:async()=>({user,csrf_token:'profile-pending-token'})});await profileWait;assert.equal(node('passwordSubmit').disabled,false);assert.equal(node('saveNameBtn').disabled,false);assert.equal(node('avatarFileInput').disabled,false);
 context.nativeFetch=()=>{pendingCalls++;return new Promise(resolve=>{resolveChange=resolve;});};const passwordWait=submit();const passwordCalls=pendingCalls;await context.saveProfile('/api/auth/profile',{method:'PATCH',body:'{}'},'nameSaveStatus','Saved');assert.equal(pendingCalls,passwordCalls,'profile cannot overlap password rotation');resolveChange({status:200,ok:true,json:async()=>({user,csrf_token:'rotation-after-profile'})});await passwordWait;assert.equal(node('passwordSubmit').disabled,false);assert.equal(node('removeAvatarBtn').disabled,false);
 context.nativeFetch=async(input,init)=>{calls.push({input,init});return {status:200,ok:true,json:async()=>({user:{...user,display_name:'Updated'},csrf_token:'profile-token'})};};
 await context.saveProfile('/api/auth/profile',{method:'PATCH',body:'{}'},'nameSaveStatus','Saved');
 assert.equal(context.session.user.display_name,'Updated');assert.equal(node('accountIdentity').textContent,'Updated');assert.equal(node('nameSaveStatus').textContent,'Saved');
 context.nativeFetch=async()=>({status:400,ok:false,json:async()=>({detail:'Invalid image'})});
 await context.saveProfile('/api/auth/avatar',{method:'PUT'},'avatarStatus','Saved');assert.match(node('avatarStatus').textContent,/Invalid image/);assert.equal(context.session.csrf_token,'profile-token');
 context.nativeFetch=async(input,init)=>{calls.push({input,init});assert.equal(init.method,'DELETE');assert.equal(init.body,'{}','delete request supplies middleware-required body');assert.equal(init.headers.get('Content-Type'),'application/json');return {status:200,ok:true,json:async()=>({user,csrf_token:'deleted-avatar-token'})};};
 vm.runInContext(source.slice(source.indexOf("el('removeAvatarBtn'"),source.indexOf("el('saveNameBtn'",source.indexOf("el('removeAvatarBtn'"))),context);
 listeners.click();await new Promise(resolve=>setImmediate(resolve));assert.equal(context.session.csrf_token,'deleted-avatar-token');assert.equal(calls.at(-1).input,'/api/auth/avatar');
 let clock=0,reduced=false,timer,nextTimer=0,dispatched=0;
 context.Date={now:()=>clock};context.matchMedia=()=>({matches:reduced});context.Event=Event;context.CustomEvent=class{constructor(type,init){this.type=type;this.detail=init.detail;}};context.window={clearTimeout(){timer=undefined;},setTimeout(fn,delay){timer={fn,delay};return ++nextTimer;}};
 context.loadingStarted=0;context.loadingGeneration=0;context.resolveLoading=undefined;context.loadingTimer=undefined;
 vm.runInContext(source.slice(source.indexOf('function authTransition('),source.indexOf('const nativeFetch')),context);
 vm.runInContext(source.slice(source.indexOf('function showLogin('),source.indexOf('function applyRole(')),context);
 vm.runInContext(source.slice(source.indexOf('async function signedIn('),source.indexOf('const ready =')),context);
 context.document.getElementById=id=>elements[id]||null;const transitions=[];context.document.dispatchEvent=event=>{if(event.type==='workspace-ready')dispatched++;else transitions.push(event.detail.active);};context.document.body={classList:{remove(value){context.removedClass=value;},add(){}}};
 context.session=null;context.entered=false;context.gate={hidden:true};assert.equal(context.gate.hidden,true,'initial gate stays hidden pending session verdict');context.signedIn({user,csrf_token:'restored-token'});assert.equal(context.gate.hidden,true,'restored session never flashes login gate');assert.equal(node('loginTransitionLoader').hidden,true,'restored sessions never show crowd loader');assert.equal(context.removedClass,'signed-out');await context.finishLoading();assert.equal(timer,undefined,'restored startup has no minimum delay');assert(!transitions.includes(true));await context.finishLoading('Restored startup failed');assert.equal(node('loginTransitionLoader').hidden,false);assert.equal(timer,undefined);context.entered=false;context.removedClass=undefined;dispatched=0;context.signedIn({user,csrf_token:'load-token'},true);
 assert.equal(node('transitionTitle').textContent,'Menyiapkan studio Anda.');assert.equal(node('loginTransitionLoader').hidden,false);assert.equal(context.removedClass,undefined);elements.loginTransitionRetry=node('loginTransitionRetry');await context.finishLoading('Cannot load');assert.equal(timer,undefined,'startup errors do not delay');assert.equal(node('loginTransitionRetry').focused,true);assert.equal(node('loginTransitionLoader').hidden,false);
 elements.workspaceTitle=node('workspaceTitle');context.loadingStarted=0;clock=1000;const reveal=context.finishLoading();assert.equal(timer.delay,2200,'minimum duration starts at sign-in');assert.equal(node('loginTransitionLoader').hidden,false);clock=3200;timer.fn();await reveal;assert.equal(node('workspaceTitle').focused,true);assert.equal(node('loginTransitionLoader').hidden,true);assert.equal(context.removedClass,'signed-out');assert.equal(dispatched,1);
 delete elements.workspaceTitle;elements.mainContent=node('mainContent');clock=5000;await context.finishLoading();assert.equal(node('mainContent').focused,true,'slow real startup needs no extra delay');
 reduced=true;clock=0;context.loadingStarted=0;node('loginTransitionLoader').hidden=false;await context.finishLoading();assert.equal(node('loginTransitionLoader').hidden,true,'reduced motion bypasses showcase delay');reduced=false;
 node('loginTransitionLoader').hidden=false;context.removedClass=undefined;const cancelled=context.finishLoading();assert(timer);const staleTimer=timer.fn;context.showLogin();staleTimer();await cancelled;assert.equal(timer,undefined);assert.equal(context.session,null);assert.equal(context.removedClass,undefined,'expired session cannot reveal dashboard');assert.equal(context.gate.hidden,false);
 context.session={user,csrf_token:'error-token'};node('loginTransitionLoader').hidden=false;const interrupted=context.finishLoading();assert(timer);await context.finishLoading('Late startup failure');await interrupted;assert.equal(timer,undefined);assert.equal(node('loginTransitionLoader').hidden,false,'error cancels pending reveal while retaining error screen');
 // Re-login after expiry shows the explicit transition before isolating old controllers by reload.
 context.location={reload(){context.reloaded=true;}};context.entered=true;context.session=null;clock=0;context.reloaded=false;
 const reentry=context.signedIn({user,csrf_token:'reentry-token'},true);assert.equal(timer.delay,3200);assert.equal(node('loginTransitionLoader').hidden,false);assert.equal(context.reloaded,false);const readyBefore=dispatched;clock=3200;timer.fn();assert.equal(await reentry,false);assert.equal(context.reloaded,true);assert.equal(dispatched,readyBefore,'reentry reload does not rerun workspace initialization');
 context.reloaded=false;clock=0;const abortedEntry=context.signedIn({user,csrf_token:'aborted-reentry'},true);context.showLogin();await abortedEntry;assert.equal(context.reloaded,false);assert.equal(timer,undefined);
 reduced=true;assert.equal(await context.signedIn({user,csrf_token:'reduced-reentry'},true),false);assert.equal(context.reloaded,true);assert.equal(timer,undefined);reduced=false;
 context.location={reload(){context.reloaded=true;}};context.session={user,csrf_token:'logout-token'};clock=0;context.reloaded=false;
 context.nativeFetch=async()=>({status:500,ok:false});await node('logoutButton').onclick();assert.equal(node('authError').hidden,false);assert.match(node('authError').textContent,/Gagal keluar/);assert.equal(node('loginTransitionLoader').hidden,true,'logout failure removes transition immediately');assert.equal(context.reloaded,false);assert.equal(node('logoutButton').disabled,false);assert.equal(context.session.csrf_token,'logout-token');
 context.nativeFetch=async()=>({status:200,ok:true});const logout=node('logoutButton').onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(timer.delay,3200);assert.equal(node('transitionTitle').textContent,'Sampai jumpa.');assert.equal(node('loginTransitionLoader').hidden,false);assert.equal(node('logoutButton').disabled,true);await context.finishLoading();assert.equal(timer.delay,3200,'startup completion cannot replace logout timer');assert.equal(node('loginTransitionLoader').hidden,false);clock=3200;timer.fn();await logout;assert.equal(context.reloaded,true);assert.equal(context.session,null);assert.equal(node('logoutButton').disabled,false);
 context.session={user,csrf_token:'expired-logout-token'};context.reloaded=false;clock=0;const expiredLogout=node('logoutButton').onclick();await new Promise(resolve=>setImmediate(resolve));context.showLogin();await expiredLogout;assert.equal(context.reloaded,false,'expiry cancels pending logout transition');assert.equal(timer,undefined);
 context.session={user,csrf_token:'401-logout'};context.reloaded=false;node('logoutButton').focused=false;node('loginUsername').focused=false;context.nativeFetch=async()=>({status:401,ok:false});await node('logoutButton').onclick();assert.equal(context.session,null);assert.equal(context.gate.hidden,false);assert.equal(node('loginError').hidden,false);assert.match(node('loginError').textContent,/Sesi berakhir/);assert.equal(node('loginUsername').focused,true);assert.equal(node('logoutButton').focused,false,'401 logout does not focus hidden workspace');assert.equal(context.reloaded,false);
 context.nativeFetch=async()=>({status:200,ok:true});
 context.session={user,csrf_token:'reduced-logout'};reduced=true;context.reloaded=false;await node('logoutButton').onclick();assert.equal(timer,undefined,'reduced-motion logout has no showcase delay');assert.equal(context.reloaded,true);reduced=false;
 vm.runInContext(source.slice(source.indexOf('function evaluatePassword('),source.indexOf('let announcementTimer')),context);
 assert.equal(context.evaluatePassword('').score,0);assert.equal(context.evaluatePassword('passwordAb!123').score,1);assert.equal(context.evaluatePassword('Zebra!Moon7').score,3);assert.equal(context.evaluatePassword('Zebra!Moon728').score,4);
 const meterAttributes={},cells=Array.from({length:4},()=>({filled:false,classList:{add(){this.owner.filled=true;},remove(){this.owner.filled=false;}}}));for(const cell of cells)cell.classList.owner=cell;
 const label={textContent:''},common={hidden:true};context.window={clearTimeout(){},setTimeout(fn){fn();return 1;}};
 context.document.getElementById=id=>id==='passwordMeter'?{setAttribute(k,v){meterAttributes[k]=v;},querySelectorAll(){return cells;},querySelector(selector){return selector==='.password-meter-label'?label:common;}}:elements[id]||null;
 vm.runInContext(source.slice(source.indexOf('let announcementTimer'),source.indexOf('async function saveProfile(')),context);
 context.updatePasswordMeter('Zebra!Moon728');assert.equal(meterAttributes['aria-valuenow'],'4');assert.equal(meterAttributes['aria-valuemax'],'4');assert.equal(cells.filter(cell=>cell.filled).length,4);assert.match(node('passwordStrengthAnnouncement').textContent,/Sangat Kuat/);
 context.updatePasswordMeter('');assert.equal(meterAttributes['aria-valuenow'],'0');assert.equal(cells.filter(cell=>cell.filled).length,0);assert.equal(node('passwordStrengthAnnouncement').textContent,'');
 console.log('PASS: password rotation/confirmation/failure/pending/cleanup, session validation, CSRF, role guard, server profile success/failure, real loading lifecycle and accessible strength meter.');
})().catch(error=>{console.error(error);process.exitCode=1;});
