'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('dashboard.js','utf8');
const pending=[];
const media={paused:true,currentTime:0,playCount:0,play(){this.paused=false;this.playCount++;return Promise.resolve();},pause(){this.paused=true;},requestVideoFrameCallback(fn){this.callback=fn;}};
const ui={};
const context={reviewVideo:media,summary:{fps:10,frames:30},job:{id:'video'},currentView:'annotation',api:()=>new Promise(resolve=>pending.push(resolve)),$:id=>ui[id]??={},showError(){},renderReviewOverlay(){},loadManualFrame(){},Map,Set,console};
vm.createContext(context);
vm.runInContext(code.slice(code.indexOf('let reviewPlaybackEpoch ='),code.indexOf('reviewVideo.onpause =')),context);
const run=s=>vm.runInContext(s,context);
(async()=>{
 run("reviewPlaybackEpoch=1;trackingSession='a';trackingJob='video';trackingWanted=true;trackingCursor=0;");
 const initial=run('prefetchTracking(1)');
 pending.shift()({frames:[{frame_index:1,boxes:[],lost:[]}],next_frame:1,ended:true});
 await initial;
 assert.equal(media.playCount,0,'initial prefetch must not create a second playback callback chain');
 run("trackingEnd=false;trackingBuffering=true;trackingCursor=0;reviewVideo.currentTime=.1;");
 const buffered=run('prefetchTracking(1)');
 pending.shift()({frames:[{frame_index:1,boxes:[],lost:[]}],next_frame:1,ended:true});
 await buffered;
 assert.equal(media.playCount,1,'only a waiting buffer resumes playback');
 assert.equal(run('trackingBuffering'),false);
 run("trackingEnd=false;trackingCursor=1;");
 const stale=run('prefetchTracking(1)');
 run("reviewPlaybackEpoch=2;trackingSession='b';trackingFrames=new Map();trackingFetch=Promise.resolve('new session');");
 const current=run('trackingFetch');
 pending.shift()({frames:[{frame_index:2,boxes:[{label:'wrong',bbox:[0,0,1,1]}],lost:[]}],next_frame:2,ended:true});
 await stale;
 assert.equal(run('trackingFrames.size'),0,'old responses must not populate a new session');
 assert.equal(run('trackingFetch'),current,'old finally callback must not clear a newer request');
 run("trackingFrames.set(2,{boxes:[{label:'karung',bbox:[.1,.1,.2,.2]}],lost:[]});trackingSuppressed=new Set([7]);analyzedFrames.set(2,{boxes:[{label:'person',track_id:7,bbox:[.1,.1,.2,.2]},{label:'car',track_id:8,bbox:[.5,.5,.6,.6]}]});");
 const labels=run('overlayAt(2).boxes.map(b=>b.label).join(",")');
 assert.equal(labels,'karung,car','manual correction must replace its original AI box without duplicating it');
 const chat=code.slice(code.indexOf("$('chatForm').onsubmit"),code.indexOf("$('chatInput').addEventListener"));
 assert(!chat.includes('startLearning'),'chat must not fine-tune YOLO automatically');
 assert(!chat.includes('persistReview(true)'),'query must not approve generated tracker boxes as training labels');
 console.log('PASS: tracking prefetch, buffering, stale response isolation, corrected overlays and query without training.');
})().catch(error=>{console.error(error);process.exitCode=1;});
