"use strict";
const assert=require('node:assert/strict');
const markup=require('./ui_markup.cjs');
const ids=[...markup.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]),known=new Set(ids);
assert.equal(ids.length,185,'all original studio controls survive React migration');
assert.equal(known.size,ids.length,'live studio IDs must be unique');
for(const [,refs] of markup.matchAll(/(?:for|aria-labelledby|aria-describedby)="([^"]+)"/g))for(const id of refs.split(/\s+/))assert(known.has(id),`accessible reference ${id} must resolve`);
for(const id of ['loginPassword','currentPassword','newPassword','confirmPassword'])assert(new RegExp(`<input[^>]*id="${id}"[^>]*type="password"`).test(markup),'password controls remain masked');
assert(!/<script|on(?:click|submit)=|dangerouslySetInnerHTML/.test(markup),'view markup never includes executable strings');
assert(/id="authGate"[^>]*hidden/.test(markup),'login stays hidden until the real session verdict to prevent refresh flash');
assert(/id="resultAi"[^>]*checked/.test(markup),'model result is selected initially');
assert(/id="reviewSvg"/.test(markup)&&/id="reviewVideo"/.test(markup),'annotation media and overlay retain their roots');
console.log('PASS: React SSR preserves 185 unique controls, accessible labels, password privacy and annotation/result contracts.');
